name: 🔄 Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with Quote
        uses: PratikBhusal/github-profile-views-counter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
